### ISSUE TITLE
Library namespace

### ISSUE THREAD

**Issue by hranicka** [stromaler/123sms.biz#3]
Current version (v1.0) has no namespace.

Shall we create a namespace for it (targetting v2.0)?

Eg. `Stromaler\Biz123Sms` or something like this?

(the first character cannot be number)

**Comment by stromajer** [comment]
:+1:

**Comment by hranicka** [comment]
I can send a pull request, no problem.

Will be `Stromaler\Biz123Sms` OK?

**Comment by stromajer** [comment]
Ok man, no probs. Let it be :tada:
